#!/usr/bin/env python2.2

# $Id$

import Main
import globals
#import profile

if __name__ == '__main__':
    import sys
    import os.path
    globals.prog = os.path.basename(sys.argv[0])
    #profile.run('Main.main(sys.argv[1:])', 'prof.out')
    Main.main(sys.argv[1:])
