#!/usr/bin/python2.2

# $Id$

#
# Quick hack to populate the mac_manu table.  Downloaded the complete list of
# ethernet manufacturer assignments, parses it, and updates the table.
#
import urllib
import os
import re
import sys
try:
    import pgdb
    dbModule = pgdb
except ImportError:
    from pyPgSQL import PgSQL
    dbModule = PgSQL

pattern = re.compile('^(\S+)\s+\(hex\)\s+(.*)')

db = dbModule.connect(database='udb',
                      #host='db.cs.brown.edu',
                      user='twh', password='changeme')

def download_file():
    sys.stdout.write("Downloading file...")
    (filename, headers) = urllib.urlretrieve('http://standards.ieee.org/regauth/oui/oui.txt')
    print filename, headers
    sys.stdout.write("done.\n")
    return filename
    
def add_manu(line):
    result = pattern.search(line)
    ether = result.group(1)
    manu = result.group(2)
    manu = manu.replace("'", "''")
    st = """INSERT INTO mac_manu (ethernet, manu) VALUES ('%s-00-00-00', '%s')""" % (ether, manu)
    dbExe(st)

def dbExe(st):
    cursor = db.cursor()
    cursor.execute(st)

if len(sys.argv) > 1:
    filename = sys.argv[1]
else:
    filename = download_file()
f = open(filename, 'r')

dbExe('DELETE FROM mac_manu')

for line in f:
    if line.find('(hex)') != -1:
        add_manu(line)
f.close()
db.commit()
db.close()

