#!/usr/bin/perl -w

use Getopt::Long;
use Pod::Usage;

use lib "/home/aleks/pro/udb/lib";
use BrownCS::UDB;

# Print a simple help message.
sub usage {
  my ($exit_status) = @_;
  pod2usage({ -exitval => $exit_status, -verbose => 99, -sections => "SYNOPSIS|DESCRIPTION|OPTIONS"});
}

sub sort_fieldnames {
  return -1 if($a eq 'hostname');
  return 1 if($b eq 'hostname');
  return $a cmp $b;
}

my $help = 0;
my $username = $ENV{'USER'};
my $udb = BrownCS::UDB->new;

GetOptions ('help|h|?' => \$help, 
            'u' => \$username) or usage(2);
usage(1) if $help;

if (@ARGV == 0) {
  usage(2);
}

my $hostname = $ARGV[0];
my $password = BrownCS::UDB->get_pass;

$udb->start($username, $password);

my %host = $udb->get_host($hostname);

print join(' ',@{$host{classes}}) . "\n";

$udb->finish;

__END__

=head1 NAME

cdb-classes - Print out the classes a host belongs to

=head1 SYNOPSIS

cdb-classes [-u username] hostname

=head1 DESCRIPTION

cdb-classes queries the UDB database for the list of classes that a host
belongs to, and prints it out to the console. It is designed to resemble
the old I<cdb classes> command.

=head1 OPTIONS

=over

=item B<-h>, B<--help>

Print a help message and exit.

=item B<-u>, B<--username>=user

Logs onto the database server as the specified username, instead of as
the current user.

=back

=head1 AUTHORS

Aleks Bromfield.

=head1 SEE ALSO

B<udb>

=cut

