#!/usr/bin/perl -w

use Getopt::Long;
use Pod::Usage;

use lib "/home/aleks/pro/udb/lib";
use BrownCS::UDB;


my $class_select = $dbh->prepare("SELECT id from comp_classes where class = ?");
my $class_insert = $dbh->prepare("INSERT INTO comp_classes (class) VALUES (?) RETURNING id");
my $class_comp_insert = $dbh->prepare("INSERT INTO comp_classes_computers (comp_classes_id, computers_id) VALUES (?,?)");
$class_comp_insert->bind_param(1, undef, SQL_INTEGER);
$class_comp_insert->bind_param(2, undef, SQL_INTEGER);

# Print a simple help message.
sub usage {
  my ($exit_status) = @_;
  pod2usage({ -exitval => $exit_status, -verbose => 99, -sections => "SYNOPSIS|DESCRIPTION|OPTIONS"});
}

sub sort_fieldnames {
  return -1 if($a eq 'hostname');
  return 1 if($b eq 'hostname');
  return $a cmp $b;
}

my $help = 0;
my $username = $ENV{'USER'};
my $udb = BrownCS::UDB->new;

GetOptions ('help|h|?' => \$help, 
            'u' => \$username) or usage(2);
usage(1) if $help;

if (@ARGV == 0) {
  usage(2);
}

my $class = shift;

my @hostnames = @ARGV;

my $password = BrownCS::UDB->get_pass;

$udb->start($username, $password);

# my %host = $udb->host($hostname);

foreach $hostname (@hostnames) {
  print "adding $hostname to $class\n";
}

$udb->finish;

__END__

=head1 NAME

cdb-class-add - Add one or more hosts to a class

=head1 SYNOPSIS

cdb-class-add [-u username] classname hostname [hostname ...]

=head1 DESCRIPTION

cdb-class-add queries the UDB database for information about a host, and
prints it out to the console. It is designed to resemble the old I<cdb
profile> command.

=head1 OPTIONS

=over

=item B<-h>, B<--help>

Print a help message and exit.

=item B<-u>, B<--username>=user

Logs onto the database server as the specified username, instead of as
the current user.

=back

=head1 AUTHORS

Aleks Bromfield.

=head1 SEE ALSO

B<udb>

=cut

