#!/usr/bin/perl -w

################################################################################
#
# Prologue
#
################################################################################

use lib "/home/aleks/pro/udb/lib";

use UDB::Common qw(init finish);
use Getopt::Long;

sub usage {
  my ($exit_status) = @_;
  print "usage: contactlist class\n\n";
  print "Prints out a contact list for all hosts in a class.\n";
  exit($exit_status);
}

my $help = 0;
my $username = $ENV{'USER'};

GetOptions ('help|h|?' => \$help, 
            'u' => \$username) or usage(2);
usage(1) if $help;

if (@ARGV == 0) {
  usage(2);
}

my $password = UDB::Common::get_pass();

UDB::Common::init($username, $password);

my(@args) = @_;
my($delim) = "\n";
my($matches) = 0;
my($first) = 1;
my($data);

printf "%-15s%-40s%-10s%-10s\n\n", "MACHINE", "SERVICES", "CONTACTS";

foreach $host (sort(keys(%$cdb_by_hostname))) {
  if (scalar(grep(($_ eq $args[0]), split(/,/, $cdb_by_hostname->{$host}{'classes'}))) > 0) {

    $services = $cdb_by_hostname->{$host}{'comment'};
    $contact = $cdb_by_hostname->{$host}{'contact'};
    printf "%-15s%-40s%-10s\n", $host, $services, $contact;
  }
}

UDB::Common::finish();

