#!/usr/bin/python2.2

# $Id$

import sys
import os.path
import udb
import TextUI

prog = os.path.basename(sys.argv[0])
try:
    if prog == 'edb':
        ui = TextUI.edb(prog)
    else:
        ui = TextUI.cdb(prog)
    ui.main(sys.argv[1:])
except KeyboardInterrupt:
    udb.rollback()
    print "\nCaught control-C"
